### ISSUE TITLE
Internal server error, possibly when a timeseries file is corrupted

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#62]
```
Internal Server Error: /timeseries/data/
Traceback (most recent call last):
  File "/usr/local/enhydris-virtualenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/enhydris-virtualenv/lib/python3.4/site-packages/enhydris/hcore/views.py", line 714, in timeseries_data
    k = iso8601.parse_date(t[0], default_timezone=tz)
  File "/usr/local/enhydris-virtualenv/lib/python3.4/site-packages/iso8601/iso8601.py", line 190, in parse_date
    raise ParseError("Unable to parse date string %r" % datestring)
iso8601.iso8601.ParseError: Unable to parse date string '2016-12-15 01:50:00  0.6717293'

Request repr(): 
<WSGIRequest
path:/timeseries/data/,
GET:<QueryDict: {'object_id': ['9541']}>,
...
```

**Comment by aptiko** [comment]
At this time, the problem cannot be reproduced and time series 9541 works fine. If, indeed, file corruption would cause an internal server error, it is not clear whether this would be a bug. It is OK for corruption to cause internal server errors, and what definitely *is* an error is for the system to allow uploading of corrupted time series, or to cause them corruption.

In the absence of more information about what had happened, I'm marking the bug "wontfix".
