### ISSUE TITLE
Adding generic data does not work

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#64]
```
Internal Server Error: /gentitygenericdata/add/
Traceback (most recent call last):
  File "/usr/local/enhydris-virtualenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/enhydris-virtualenv/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/enhydris-virtualenv/lib/python3.4/site-packages/enhydris/hcore/views.py", line 1333, in gentitygenericdata_add
    return _gentitygenericdata_edit_or_create(request)
  File "/usr/local/enhydris-virtualenv/lib/python3.4/site-packages/enhydris/hcore/views.py", line 1315, in _gentitygenericdata_edit_or_create
    str(ggenericdata.gentity.id)}))
  File "/usr/local/enhydris-virtualenv/lib/python3.4/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/enhydris-virtualenv/lib/python3.4/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'station_detail' with arguments '()' and keyword arguments '{'object_id': '1423'}' not found. 1 pattern(s) tried: ['stations/d/(?P<pk>\\d+)/$']

Request repr(): 
<WSGIRequest
path:/gentitygenericdata/add/,
GET:<QueryDict: {'station_id': ['1423']}>,
...
```

**Comment by aptiko** [comment]
Duplicate of #66.
